Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "matrix"
  config.vm.provider "hyperv" do |hyperv|
    hyperv.vmname = "matrix"
    hyperv.memory = 4096
  end
end